"""DealerPrice model: field is_marked changed to nullable

Revision ID: 116252ef8a00
Revises: b9bef4312003
Create Date: 2023-12-08 00:12:28.815270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '116252ef8a00'
down_revision: Union[str, None] = 'b9bef4312003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
