"""Fix Product model: added optional fields

Revision ID: 7577884a97f2
Revises: 2215cc4fdea8
Create Date: 2023-12-05 22:14:00.991199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7577884a97f2'
down_revision: Union[str, None] = '2215cc4fdea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
